### ISSUE TITLE
求指导

### ISSUE THREAD

**Issue by SmartYou1995** [duanzhichao/IPTV-of-TianJin-Telecom#1]
你好，大佬😳有没有天津电信组播配置的教程呀  需要爱快还是openwrt还是老毛子😄

**Comment by duanzhichao** [comment]
不论openwrt，爱快，还是老毛子，组播转代理流程各个省份运营商都是一样的，百度一下

**Comment by duanzhichao** [comment]
我这里用老毛子，简单流程说一下

1.在光猫里解除iptv的光猫端口绑定

2.将拨号桥接划分vlan绑定到一个千兆口

3.将iptv拨号划分vlan绑定到同一个千兆口

4.老毛子拨号，区分vlan，填入你的vlan值

5.这种情况下就能用rtp访问iptv了

6.在老毛子内部网络-iptv，打开代理，然后就能在各个设备用   http://路由地址:代理端口/udp/电视台地址   观看了

**Comment by SmartYou1995** [comment]
感谢  了解了  改天试一下
