### ISSUE TITLE
感谢大佬

### ISSUE THREAD

**Issue by SmartYou1995** [duanzhichao/IPTV-of-TianJin-Telecom#2]
感谢大佬，我自己搞完了  可以啦
但是发现DOX的几个频道都失效了，再扫也没扫到  应该是下架了。
另外，这种rtp源可以会看或者时移吗

**Comment by duanzhichao** [comment]
有的频道地址是在的，不过不能访问

rtp地址不可以时移和回看

**Comment by SmartYou1995** [comment]
好滴
